# .github/workflows/easypanel.yml
name: 🛠️ Install EasyPanel on server

jobs:
  install-easypanel:
    runs-on: ubuntu-latest
    steps:
      - name: Install EasyPanel on server
        uses: appleboy/ssh-action@master
        with:
          script: |
            curl -sSL https://get.easypanel.io | sh
